# Array vs List

Array: It is an linear data structure which stores the similar data type in contiguous memory.

List: Is is a linear data structure which stores any kind of data type in non contigous memory.

Both are used to for storing data.

Both are mutable. (We can change after creation)

Can be indexed.

We can perform slicing operations.


### Iteration

Iteration through array is faster than list
An array is faster and that is because ArrayList uses a fixed amount of array. However when you add an element to the ArrayList and it overflows. It creates a new Array and copies every element from the old one to the new one

In [2]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
l = [1, 2, 3]

In [6]:
a

array([1, 2, 3])

In [7]:
l

[1, 2, 3]

In [8]:
l.append(4)
l

[1, 2, 3, 4]

In [23]:
a.append(4)    # here we append, we will get an error and we can't append an array to an array, if we want to append
               # we have create new array 

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [13]:
new_a = np.append(a, 4)
new_a

array([1, 2, 3, 4])

# For a data structure to be faster that length has to be fixed. 

Array and List both are mutable, which means elements can be changed at any time, without modifying the length of the data structure.

Here, Array length can't be changed, where as list length can be changed. 

If we want to change the length of an array we have create a new array and append an element into that. In list we need not to create new list to append an element, just adds at the end.


.

## Addition 

In [15]:
l + [5]     # here adding a list means it appends list 

[1, 2, 3, 4, 5]

In [18]:
l + 5     # when we add an element we will get an error

TypeError: can only concatenate list (not "int") to list

In [16]:
a + np.array(5)     # if we add an array of single element or an element it gets added for each element in the array

array([6, 7, 8])

In [17]:
a + 5

array([6, 7, 8])

In [19]:
a + np.array([1, 2, 3])    # it gets accoring to the index, for list just get append

array([2, 4, 6])

## Multiplication

In [20]:
l*2    # it copies that many times in the same list

[1, 2, 3, 4, 1, 2, 3, 4]

In [33]:
a*2    # it multiplies each and every element with that number, if we use same size array then multiplies like dot 
       # a vector. Not only this but also subtraction and division is also same

array([2, 4, 6])

In [25]:
a**2     # powering up of 2 each and every element. In list it is not possible, if we want to use that we have to 
         # iterate through the list and power up

array([1, 4, 9])

## Other mathematical operations

In [26]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [30]:
np.log(a)   # natural log

array([0.        , 0.69314718, 1.09861229])

In [29]:
np.tanh(a)

array([0.76159416, 0.96402758, 0.99505475])